name: 'bb5e'
version: 0.0.1
description: Material Design Lite 'Android Dot Com' Template
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  mdl: any
  logging: any
  logging_handlers: any
  console_log_handler: any
  di: any

transformers:
  - di
