name: 'bb5e'
version: 0.0.1
description: Battle Buddy 5e
#author: <your name> <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any
  event_bus: any
  intl: any
  redstone: any
  redstone_web_socket: any
  http: any
  firebase: any
  firebase_rest: any
  bootstrap: any
  logging: any
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter